# Copyright 2024 Roy(徐武) <ixw1991@126.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/xwlearn/miniokr.

openapi: 3.1.0
servers:
  - url: http://127.0.0.1:8999/api/v1
    description: development server
info:
  version: "1.0.0"
  title: miniokr api definition
  description: The API for the miniokr project
  contact:
    name: Roy Xu
    email: ixw1991@126.com
    url: https://github.com/xwlearn
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /auth/dingtalk:
    post:
      tags:
        - auth
      summary: Authenticate user via DingTalk authorization code and return JWT token
      description: This endpoint receives a temporary authorization code from DingTalk (obtained by the frontend), authenticates the user, and returns a JWT token if successful.
      requestBody:
        required: true
        content:
          application/json:
            schema:
            $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: successfully auth
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/AuthResponse'
        '400':
          description: request failed due to client-side problem
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/ErrResponse'
        '500':
          description: request failed due to server-side problem
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/ErrResponse'

  /fields:
    get:
      tags:
        - field
      summary: Get field mappings for all tables
      description: Returns a mapping of friendly English names to Chinese names for Objective and KeyResult tables.
      operationId: getFields
      responses:
        '200':
          description: A map of table names to their respective fields' mappings.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldMappingsResponse'

  components:
    schemas:
      AuthRequest:
        type: object
        required:
          - authCode
        properties:
          authCode:
            type: string
            description: The temporary authorization code obtained from DingTalk.
      AuthResponse:
        type: object
        properties:
          token:
            type: string
            description: The JWT token generated for the authenticated user.
            example: xxx.yyy.zzz
      FieldMappingsResponse:
        type: object
        properties:
          objective:
            $ref: '#/components/schemas/ObjectiveFields'
          keyresult:
            $ref: '#/components/schemas/KeyResultFields'
      ObjectiveFields:
        type: object
        properties:
          title:
            type: string
            example: 'O 的内容填写'
          owner:
            type: string
            example: '员工姓名'
          date:
            type: string
            example: '考核月份'
          weight:
            type: string
            example: 'O 的权重'
      KeyResultFields:
        type: object
        properties:
          title:
            type: string
            example: 'KR 的内容'
          weight:
            type: string
            example: 'KR 的权重'
          completed:
            type: string
            example: '是否完成'
          description:
            type: string
            example: '关键结果描述'
      ErrResponse:
        type: object
        properties:
          code:
            type: integer
            format: int64
            example: 10001/20002
          message:
            type: string
            example: "Internal server error./Validation failed."
          
            

